repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the latest version of Prettier
    hooks:
      - id: prettier
